### ISSUE TITLE
Audio Gap When SFX Loops

### ISSUE THREAD

**Issue by JohannPopper** [rafaelmardojai/blanket#111]
Greetings. Thank you for this serene application. I wish to report a bug in the latest flatpak version that I've observed on the latest versions of Fedora and Ubuntu. When each audio SFX clip reaches the end (including custom sounds), it does not immediately loop, but rather there is an audible gap of ~1 second before it begins to play again. Therefore, the sounds can be quite jarring every ~8 seconds. It's most noticeable with those SFX with consistent sound, like rain or wind. Seems like the background player is not seamlessly looping the oggs, which is the expected behavior.

Thank you for your time.

**Comment by rafaelmardojai** [comment]
Probably is the same issue from #67, could you test the flatpak from last commit? https://github.com/rafaelmardojai/blanket/suites/2480054582/artifacts/53399603

**Comment by rafaelmardojai** [comment]
> Probably is the same issue from #67, could you test the flatpak from last commit? https://github.com/rafaelmardojai/blanket/suites/2480054582/artifacts/53399603

The new version `0.4.0` also contain those fixes, let me know if the issue continues.

**Comment by JohannPopper** [comment]
I apologize for disappearing for a few days. I just tested the latest release (which is really fantastic and superior in a number of other ways to previous versions). Seems to work perfectly so far. Thank you!
