### ISSUE TITLE
Nothing happens on opening blanket

### ISSUE THREAD

**Issue by preIdiot** [rafaelmardojai/blanket#119]
I installed blanket on my Ubuntu 20.04  using the PPA but on running it nothing happens. I have installed all the dependencies but still, nothing works.
Help!

**Comment by rafaelmardojai** [comment]
You get something running Blanket from terminal?

CC @apandada1

**Comment by apandada1** [comment]
Works for me in KDE Neon 20.04 (based on Ubuntu 20.04). The PPA ships libhandy1, and any other missing dependencies are supposed to be automatically installed during installation of blanket. We need the terminal output.

**Comment by preIdiot** [comment]
Okay, now it is working, after a system restart. When I installed it earlier it was showing something like "blanket is not a terminal application" on running "blanket" on the terminal. Thanks for the assistance.
