### ISSUE TITLE
Close and License buttons on About window do not function [Linux]

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#13]
They simply don't function: Close does not close and License does not show the license.

Manjaro Linux, MATE graphical environment, installed via AUR (ArchLinux User Repository)

**Comment by apandada1** [comment]
Confirmed in Linux Mint 20 Cinnamon.

**Comment by rafaelmardojai** [comment]
The Keyboard Shortcuts window has the same issue? 

Do you have the standard GTK About window or is patched downstream? 
![Captura de pantalla de 2020-09-11 13-50-51](https://user-images.githubusercontent.com/6210397/92961982-d4de3d80-f435-11ea-9e3b-ee2d60649cbe.png)

**Comment by apandada1** [comment]
It's patched.
![Screenshot from 2020-09-12 00-27-14](https://user-images.githubusercontent.com/3063132/92962737-edb01880-f460-11ea-83e5-659ed9e1088b.png)

**Comment by Porrumentzio** [comment]
I have the same as @apandada1 in Mate

**Comment by rafaelmardojai** [comment]
I was able to reproduce by setting `gtk-dialogs-use-header` to `False` on `GtkSettings`.

Now I need to figure out why `Licence` button is showing up and `Close` button isn't destroying the dialog.

**Comment by rafaelmardojai** [comment]
Should be fixed now. Please test and confirm.

**Comment by apandada1** [comment]
Fixed in Cinnamon. Close button works, and License button is not there anymore.
![fixed](https://user-images.githubusercontent.com/3063132/92986802-fe867b80-f4ac-11ea-810d-0f83e26bb154.png)

**Comment by Porrumentzio** [comment]
Also worked on MATE, thanks Rafael!

**Comment by rafaelmardojai** [comment]
> I am backporting this fix to the stable PPA.

Released `0.3.1` with bug fixes.

**Comment by apandada1** [comment]
Now that these bugs have been fixed and there are interesting new features, it may be a good time to inform OMG Ubuntu once again.
