### ISSUE TITLE
Add the Finnish translation of the app

### ISSUE THREAD

**Issue by heidiwenger** [rafaelmardojai/blanket#134]
I have the Finnish .po -file done, but i can't seem to make a a new pull request / upload.

**Comment by rafaelmardojai** [comment]
What are the difficulties you're experiencing? 

In any case you can send me the translation here attaching a `.zip` or send it to my email `email [at] rafaelmardojai [dot] com`.

**Comment by jose1711** [comment]
Finnish translation was added on May 25th so perhaps this can be closed.
