### ISSUE TITLE
MPRIS integration and background playback

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#14]
It would be great to close the app but that it remain running, with a tray icon, for computers.

**Comment by GammaGames** [comment]
I would prefer integration as a media player so it would show up in system sound menus instead. Even dock integration would be better than a system indicator.

[Here's some more reading on why tray icons aren't good designs for apps](https://elementary.io/docs/human-interface-guidelines#system-indicators)

**Comment by rafaelmardojai** [comment]
I will provide MPRIS integration and an option to keep playing when closed.
