### ISSUE TITLE
[Proposal] Add general volume fader

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#15]
This feature would be good because, otherwise, is more difficult to adjust the sound.

**Comment by rafaelmardojai** [comment]
Added on the new app menu:
![Captura de pantalla de 2020-09-03 16-15-30](https://user-images.githubusercontent.com/6210397/92172201-3c2a3b00-ee01-11ea-8a36-06f3a234ce31.png)

**Comment by Porrumentzio** [comment]
Great! I'm closing this issue, thanks :)
