### ISSUE TITLE
[Proposal] Shortcut to stop the sound

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#16]
As music players do, using the "play/resume" keyboard shortcut to stop the sound would be very comfortable

**Comment by renestalder** [comment]
Or I would already appreciate a pause button in the UI itself. That would make it easier to pause and resume later than realigning the sliders.

**Comment by Porrumentzio** [comment]
Also, of course. I propose a general volume fader too: #15

**Comment by rafaelmardojai** [comment]
I have added a play/pause action, it can be activated from the headerbar and soon with the MPRIS control. 

The action also have the `Ctrl + M` (mute) keyboard shortcut.

![Peek 03-09-2020 08-44](https://user-images.githubusercontent.com/6210397/92152765-d5992300-ede8-11ea-88f8-387b9a74b6c5.gif)

**Comment by Porrumentzio** [comment]
That's great! Thanks Rafael!

**Comment by renestalder** [comment]
Awesome. Thank you.
