### ISSUE TITLE
Preset menu: More spacing left of check

### ISSUE THREAD

**Issue by bertob** [rafaelmardojai/blanket#187]
The check indicating the selected item is too close to the label, it needs 6 or 12px horizontal spacing:

![image](https://user-images.githubusercontent.com/1908896/135162536-5e43db6f-06b4-423f-8c31-dc9e34b63aee.png)

**Comment by rafaelmardojai** [comment]
Hmm, this icon also has changed right? Looks like I didn't notice this because was smaller.

**Comment by bertob** [comment]
It has, yeah. The problem with this icon is that we're using it both for selection mode in the headerbar and inline cases like this. For the latter we should have a second icon that's smaller, while the former should probably be even larger. Splitting that up into two icons is on my list, but you'll need more spacing here regardless :)

**Comment by rafaelmardojai** [comment]
`6px` seems enough right?

![Captura de pantalla de 2021-09-28 16-26-57](https://user-images.githubusercontent.com/6210397/135168155-08be34c3-e7c8-470d-ba6e-965464909d4a.png)
