### ISSUE TITLE
Gstreamer 1.20 issue

### ISSUE THREAD

**Issue by Tuxino88** [rafaelmardojai/blanket#199]
![Schermata da 2021-10-21 11-44-56](https://user-images.githubusercontent.com/75674245/138253674-06852e65-afda-41d5-8c76-0d8cf91f1d51.png)

<details>

/usr/share/blanket/blanket/sound.py:86: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_volume(0)
/usr/share/blanket/blanket/sound.py:89: Warning: g_object_setv: assertion 'G_IS_OBJECT (object)' failed
  self.set_uri(self.sound.uri)
/usr/share/blanket/blanket/sound.py:94: Warning: g_object_get_property: assertion 'G_IS_OBJECT (object)' failed
  self.pipeline = self.get_pipeline()
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'
/usr/share/blanket/blanket/widgets.py:194: Warning: g_object_is_floating: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)

(python3:8181): Gtk-CRITICAL **: 11:41:17.145: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.145: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
/usr/share/blanket/blanket/widgets.py:194: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.model.append(sound)
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.146: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.146: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.147: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.147: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.148: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.148: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.149: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.149: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.149: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.149: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.150: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.150: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.151: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.151: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.152: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.152: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.153: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.153: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.153: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.153: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.154: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.154: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.155: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.155: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/widgets.py", line 197, in _create_sound_widget
    widget = SoundRow(sound, self.model)
  File "/usr/share/blanket/blanket/widgets.py", line 61, in __init__
    self.player = SoundPlayer(self.sound)
  File "/usr/share/blanket/blanket/sound.py", line 95, in __init__
    bus = self.pipeline.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'

(python3:8181): Gtk-CRITICAL **: 11:41:17.156: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(python3:8181): Gtk-CRITICAL **: 11:41:17.156: gtk_list_box_insert: assertion 'GTK_IS_WIDGET (child)' failed

</details>

1. gtk4.x86_64                                                 4.4.0-4.fc35 
2. libadwaita.x86_64                                           1.0.0-0.7.alpha.3.fc35                                           
3. meson.noarch                                                0.59.1-1.fc35                       
4. python3.x86_64                                                              3.10.0-1.fc35

**Comment by wangxa** [comment]
self.pipeline is **None**. GstPlayer.Player, the class impored by typelib of gstreamer1-plugin-bad has changed its implementation.

**Comment by pitlochry** [comment]
I can confirm this behaviour. @wangxa thanks for the information. But what should I do to make it work again?

**Comment by wangxa** [comment]
If this only occurs under Fedora 35, I guess it is caused by pipewire.

**Comment by pitlochry** [comment]
This problem started after updating to Fedora 35. So your guess may be right.

**Comment by Tuxino88** [comment]
any news?

**Comment by Tuxino88** [comment]
> Same problem on Arch now.

Abandonware?

**Comment by rafaelmardojai** [comment]
> Abandonware?

Not really, the GNOME 42 flatpak runtime was released today, so these next weeks I will finishing the new version and releasing it.

It's true that the development has been a bit slow lately, and I don't have time to test this kind of issues outside flatpak, but if six months for a release is too much, then GNOME is abandonware?

**Comment by Tuxino88** [comment]
> > Abandonware?
> 
> Not really, the GNOME 42 flatpak runtime was released today, so these next weeks I will finishing the new version and releasing it.
> 
> It's true that the development has been a bit slow lately, and I don't have time to test this kind of issues outside flatpak, but if six months for a release is too much, then GNOME is abandonware?

not receiving a response since October I thought the project was less dead, all here, no other reason

**Comment by rafaelmardojai** [comment]
@Tuxino88 What version of GStreamer do you have?

Everything still works fine in flatpak I will try to test in a fedora toolbox later.

I don't know why `GstPlayer.Player.get_pipeline` is returning `None`.

**Comment by rafaelmardojai** [comment]
Reproduced the issue with a fedora toolbox. Porting the app to use `GstPlay` seems to fix the issue.

**Comment by Tuxino88** [comment]
> @Tuxino88 What version of GStreamer do you have?
> 
> Everything still works fine in flatpak I will try to test in a fedora toolbox later.
> 
> I don't know why `GstPlayer.Player.get_pipeline` is returning `None`.

Gstreamer 1.20.0

**Comment by rafaelmardojai** [comment]
Porting to the `GstPlayer` replacement `GstPlay` from 1.20 fix the issue, but I can't simply do that, there's no Gstreamer 1.20 in any flatpak runtime at this time.

I will try to figure out some workaround that works in both `1.18` and `1.20`.

**Comment by rafaelmardojai** [comment]
@Tuxino88 could you test [4cc08174b486f7b78c57633877c79f6a910f28ff]?

**Comment by Tuxino88** [comment]
> @Tuxino88 could you test [[4cc0817](https://github.com/rafaelmardojai/blanket/commit/4cc08174b486f7b78c57633877c79f6a910f28ff)]?

Ok , now work again.

only print this output on terminal

/usr/share/blanket/blanket/sound.py:6: PyGIWarning: GstPlay was imported without specifying a version first. Use gi.require_version('GstPlay', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository.GstPlay import Play as GStreamerPlay

the version should be specified

**Comment by rafaelmardojai** [comment]
> Ok , now work again.
> 
> only print this output on terminal
> 
> /usr/share/blanket/blanket/sound.py:6: PyGIWarning: GstPlay was imported without specifying a version first. Use gi.require_version('GstPlay', '1.0') before import to ensure that the right version gets loaded. from gi.repository.GstPlay import Play as GStreamerPlay
> 
> the version should be specified

I know, but is just an small warning.

I can't use `gi.require_version` because if GStreamer `1.18` is used then it will fail because `GstPlay` isn't available.

**Comment by J0nnyMak0** [comment]
> @Tuxino88 could you test [[4cc0817](https://github.com/rafaelmardojai/blanket/commit/4cc08174b486f7b78c57633877c79f6a910f28ff)]?

For some reason, this still does not work for me. I wonder if something needs to be done to make this change work with pipewire.

**Comment by Tuxino88** [comment]
> > @Tuxino88 could you test [[4cc0817](https://github.com/rafaelmardojai/blanket/commit/4cc08174b486f7b78c57633877c79f6a910f28ff)]?
> 
> For some reason, this still does not work for me. I wonder if something needs to be done to make this change work with pipewire.

please provide the logs

**Comment by pitlochry** [comment]
I can confirm that it works now on fedora 36 beta (which has pipewire). Thanks for the update. 
@Tuxino88 perhaps you can test on a live system of your distribution if the problem is still present?

**Comment by Tuxino88** [comment]
> @Tuxino88 perhaps you can test on a live system of your distribution if the problem is still present?

? I'm on fedora and it works

**Comment by pitlochry** [comment]
So sorry, I meant @J0nnyMak0, of course. I mixed it up.

**Comment by J0nnyMak0** [comment]
> @J0nnyMak0 perhaps you can test on a live system of your distribution if the problem is still present?

I'm not sure what you mean by live system. I'm building from source. Is there a way I can produce some logs?

**Comment by Tuxino88** [comment]
Open a new issues related to your problem
