### ISSUE TITLE
No way to localize “Add Custom Sound...” button

### ISSUE THREAD

**Issue by LeftyDeMilo** [rafaelmardojai/blanket#207]
There is a message string "Add Custom Sound" (without ellipsis) in pot file, but it does not change text on the button.

![Add Custom Sound](https://user-images.githubusercontent.com/71212608/140636088-8d76d7eb-8720-46de-85ff-62d847d81867.png)

**Comment by rafaelmardojai** [comment]
Thanks, looks like I forgot to add the file that contains that string to the `POTFILES`.

> There is a message string "Add Custom Sound" (without ellipsis) in pot file, but it does not change text on the button.

Yeah, that one is for the file chooser title.
