### ISSUE TITLE
Fails to build from source in Launchpad

### ISSUE THREAD

**Issue by apandada1** [rafaelmardojai/blanket#21]
I made a debian package for blanket, but faced an issue. While it builds successfully in my computer (tried with Xubuntu 20.04 and Linux Mint 20), it fails to build in the Launchpad server (where I tried to make a PPA).
Here is the relevant part of the buildlog.
```
The Meson build system
Version: 0.53.2
Source dir: /<<PKGBUILDDIR>>
Build dir: /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu
Build type: native build
Project name: blanket
Project version: 0.2.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Program desktop-file-validate found: NO
Program appstream-util found: NO
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Program python3 found: YES (/usr/bin/python3)
Configuring blanket using configuration
Program build-aux/meson/postinstall.py found: YES (/<<PKGBUILDDIR>>/build-aux/meson/postinstall.py)
Build targets in project: 6

Found ninja-1.10.0 at /usr/bin/ninja
   dh_auto_build
	cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 ninja -j4 -v
[1/3] glib-compile-resources ../data/resources/blanket.gresource.xml --sourcedir ../data/resources --internal --generate --target data/resources/blanket.gresource --dependency-file data/resources/blanket.gresource.d
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
[2/3] /usr/bin/meson --internal msgfmthelper ../data/com.rafaelmardojai.Blanket.metainfo.xml.in data/com.rafaelmardojai.Blanket.metainfo.xml xml ../data/../po
FAILED: data/com.rafaelmardojai.Blanket.metainfo.xml 
/usr/bin/meson --internal msgfmthelper ../data/com.rafaelmardojai.Blanket.metainfo.xml.in data/com.rafaelmardojai.Blanket.metainfo.xml xml ../data/../po
msgfmt: cannot locate ITS rules for ../data/com.rafaelmardojai.Blanket.metainfo.xml.in
[3/3] /usr/bin/meson --internal msgfmthelper ../data/com.rafaelmardojai.Blanket.desktop.in data/com.rafaelmardojai.Blanket.desktop desktop ../data/../po
ninja: build stopped: subcommand failed.
```

Here is the [full buildlog](https://launchpadlibrarian.net/496505472/buildlog_ubuntu-focal-amd64.blanket_0.2.0-0~202009060852~ubuntu20.04.1_BUILDING.txt.gz).

Any idea what might have caused the problem? Am I missing some build dependency? 

Once this is fixed, I will send a pull request to update the `Other Methods of Installation` section in the readme with instructions for the PPA.

**Comment by rafaelmardojai** [comment]
Probably you need `appstream-glib-devel`?

**Comment by apandada1** [comment]
That did not work. I used this package. https://packages.ubuntu.com/focal/libappstream-glib-dev

**Comment by apandada1** [comment]
I will try that. In the meanwhile, please have a look at https://mail.gnome.org/archives/vala-list/2017-April/msg00048.html

**Comment by rafaelmardojai** [comment]
> I will try that. In the meanwhile, please have a look at https://mail.gnome.org/archives/vala-list/2017-April/msg00048.html

Yeah, i have been checking that too.

Similar issue: https://github.com/bilelmoussaoui/nautilus-git/issues/25

**Comment by apandada1** [comment]
Failed even after adding `appstream-util`. I am confused why it successfully builds in my PC, but fails in Launchpad. All the build dependencies I am using right now are 
```
desktop-file-utils, gettext, meson (>= 0.50), pkg-config, libglib2.0-dev, libappstream-glib-dev, appstream-util
```

**Comment by rafaelmardojai** [comment]
Do you have a way to check out how other similar apps like Lollypop are packaged?

**Comment by apandada1** [comment]
I made it based on the debian directory structure of [Foliate](https://github.com/johnfactotum/foliate), whose PPA I maintian. I will look into Lollypop.

**Comment by apandada1** [comment]
I am using the same debian structure as Lollypop or Foliate (could not determine if anything is different), and they build correctly in Launchpad.
The same issue is present when I try to build with pbuilder (in my computer) inside a `chroot` environment. Not sure what is different outside the chroot environment.

**Comment by apandada1** [comment]
In Debian, the dependency is `appstream` (it comes preinstalled with most operating systems, that is why it was so hard to isolate). All credit goes to [Colin Watson](https://answers.launchpad.net/launchpad/+question/692788), who answered this [question](https://answers.launchpad.net/launchpad/+question/692788).

I have checked that the package builds locally in an isolated environment. I will soon send a pull request with information about the debian package. I will also update the dependencies in the readme.

**Comment by apandada1** [comment]
@rafaelmardojai By the way, is python-gobject really required as a dependency? In my computer, Blanket runs without it, and it is not required to build Blanket either.

**Comment by rafaelmardojai** [comment]
The dependency is **PyGObject**, in Fedora is packaged as `python3-gobject` and in Arch as `python-gobject`. I don't know the package name in Ubuntu. 

I will update the README to `python3-gobject`.

**Comment by rafaelmardojai** [comment]
But since Python 2 is deprecated, I don't know if it's better to leave it like this.
