### ISSUE TITLE
Respect Dark Style Preference

### ISSUE THREAD

**Issue by Libric0** [rafaelmardojai/blanket#218]
Hi!

When I use adwaita dark- I have to manually toggle dark mode. As Gnome 42 will have a dark-style preference, it would be good if the standard option would be to use the system style preference for the accent colors (And the accent colors for that matter)

Thank you for your great work!

**Comment by rafaelmardojai** [comment]
I haven't understand well what do you mean, but in the GTK4 port (current `master` branch) aimed for GNOME 42, Blanket doesn't longer exposes a dark mode toggle for systems that support the new preference, so it will follow the system style.
