### ISSUE TITLE
Swich Preset

### ISSUE THREAD

**Issue by oyajun** [rafaelmardojai/blanket#224]
When we swich preset, we have to click 3 times.
I don't think it is easy.

So,do you think of my idea?
![Screenshot from 2022-01-14 00-35-04](https://user-images.githubusercontent.com/81346541/149363388-0a15d239-2c27-45f7-9d7c-f9ff890a9670.png)

**Comment by gregorni** [comment]
@rafaelmardojai What do you think? I might work on this if you think it's a good idea.

**Comment by rafaelmardojai** [comment]
@gregorni There's a redesign going on that kinds of resolve this. See #288.

**Comment by gregorni** [comment]
Oh nice! Then I won't reinvent the wheel.
