### ISSUE TITLE
Add icons for custom sounds

### ISSUE THREAD

**Issue by tronta** [rafaelmardojai/blanket#229]
It would make it easier imho to switch on/off custom sounds with an additional icon/button.

My kids also are fans of this app and we play with it also on my Linux phone.
One thing which could be improved, is to make it easier to understand and to handle own sounds by adding a generic icon/button. As I remember, you had something similar in place. But when fiddling around on it especially with a touch screen, sth like this, would make it much easier.

There is no need to switch the icon, but always keep a loudspeaker shape.

What do you think?

![grafik](https://user-images.githubusercontent.com/5135577/152683187-e9ab7599-35a1-458d-88d3-5a61364d3cdc.png)

**Comment by rafaelmardojai** [comment]
Yep I plan to do that, but didn't have time in the last release. We already have the icon for that.

**Comment by moan0s** [comment]
A bonus would be to be able to add an icon for a specific custom sound. I use this for Dungeons and Dragons and it would be amazing to additional mark my sounds to quickly select one by theme.
My workaround is to use an emoji in the filename
![Screenshot showing a custom sound with an emoji at the beginning](https://user-images.githubusercontent.com/25753802/153246480-26183610-da2a-42cf-869b-b409fb988cb1.png)

**Comment by rafaelmardojai** [comment]
> A bonus would be to be able to add an icon for a specific custom sound. I use this for Dungeons and Dragons and it would be amazing to additional mark my sounds to quickly select one by theme.

This has been asked before, but I really want to avoid adding to much complexity to the app. I will prefer to invest my limited free time on improving the sound side of the app.

**Comment by moan0s** [comment]
Very understandable :) How would you feel about a merge request that implements this (not that I have time rn or any idea if I could do that)

**Comment by rafaelmardojai** [comment]
> Very understandable :) How would you feel about a merge request that implements this (not that I have time rn or any idea if I could do that)

I don't think that could work, icons should be recolorable to represent the active state.
