### ISSUE TITLE
Remove white and pink noise

### ISSUE THREAD

**Issue by tronta** [rafaelmardojai/blanket#230]
I'm not sure about the use case you had in mind when you added white and pink noise, but I personally would never mix them with any of the other sounds.

So from my perspective, I would simply remove them.

**Comment by rafaelmardojai** [comment]
Noise sounds are one of the reason why this app exist in the first place, even generating the noise in runtime is planned. But probably are not meant to be mixed with other sounds.

I could build a special view for noises that only allows you activate one at a time. But until I have time for that, having them in the main view is the best I can do.

**Comment by tronta** [comment]
I understand.
