### ISSUE TITLE
Why is fireplace inside of the interiors group

### ISSUE THREAD

**Issue by IlijazM** [rafaelmardojai/blanket#238]
Why is fireplace inside of the interiors group? It seams very dangerous to put a fireplace there. In order not to give people stupid ideas, the fireplace should be in a outdoors group or in the nature group.

**Comment by rafaelmardojai** [comment]
I didn't know there were outdoor fireplaces, I thought they were called "bonfire".

Well the sound is about this kind of fireplaces :P

![Biltmore-Wood-Burning-Fireplace-2-main__66102.1541203315.jpg](https://user-images.githubusercontent.com/6210397/156581026-216a8474-f480-435a-82f9-8c0afe743f24.jpg)

**Comment by IlijazM** [comment]
Oh ok I thought of fireplaces like this:

![](https://user-images.githubusercontent.com/35637072/157470834-bee982f0-6452-428d-8597-9fc985ae3a70.png)

But now it makes sense to me.

Yeah maybe the icon can be changed to something like that:

![](https://user-images.githubusercontent.com/35637072/157471300-35721f2d-fcdb-4d4b-9e2e-b3c04b7f2e60.png)

in order to avoid someone burning down their house :)

**Comment by rafaelmardojai** [comment]
@jimmac just tagging you in case you're interested on improving the iconography representation of this sound and potentially saving lives :P

**Comment by jimmac** [comment]
Making the distinct object smaller seems like going against what iconography is supposed to be about. We don't use old style telephones and yet the classic telephone speaker seems to remain being the best symbol for making calls. Open fire does a much better better job identifying the sound.
