### ISSUE TITLE
Metainfo description should be longer

### ISSUE THREAD

**Issue by razzeee** [rafaelmardojai/blanket#242]
I don't feel like the description accurately covers what this app can do and it should probably mention some of the sounds that are available.

Another approach would be to have more keywords in the .desktop file

Some context, I'm redoing the flathub search and it would have been nice to search for "rain" or "white noise" and find this. (noise is already in the keywords, but that wasn't enough for the old search)

**Comment by rafaelmardojai** [comment]
Something like this?

```
Improve focus and increase your productivity by listening to different sounds.
Also can help you to fall asleep in a noisy environment.

Features:
- Save presets
- Add custom sounds
- Auto start in background
- MPRIS integration

Included Sounds:
- Birds
- Boat
- City
- Coffee Shop
- Fireplace
- Pink noise
- Rain
- Summer Night
- Storm
- Stream
- Train
- Waves
- White Noise
- Wind
```

**Comment by razzeee** [comment]
Yes, I do think that would be far better :+1:
