### ISSUE TITLE
Dark mode toggle not working

### ISSUE THREAD

**Issue by Ch-Rad** [rafaelmardojai/blanket#244]
The dark mode toggle in preferences does not switch the appearance to dark theme. Installed using flatpak on fedora 35.

Also tried building from source but the dark mode toggle was absent from preferences.

![image](https://user-images.githubusercontent.com/74552248/161432190-887f71bf-c269-4126-bf8c-2991547d6ac8.png)

**Comment by 0x6e656b6f** [comment]
You can force a GTK theme in flatpak by using flatpak override --env=GTK_THEME=your-theme or using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) under Environment Variables. Keep in mind that you need to install the respective theme first.

**Comment by Ch-Rad** [comment]
> You can force a GTK theme in flatpak by using flatpak override --env=GTK_THEME=your-theme or using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) under Environment Variables. Keep in mind that you need to install the respective theme first.

Thanks it worked.

**Comment by tobia** [comment]
To summarize for others, this is what worked for me:
```
flatpak install org.gtk.Gtk3theme.Adwaita-dark
flatpak override --env GTK_THEME=Adwaita-dark
```
Now if I could figure out how to make it use the standard window decorations that every other app on my system has... but that's a different issue and much ink has already been spilled about it.
