### ISSUE TITLE
Translation moved to Transifex

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/blanket#248]
Hey translators! 

Just wanted to let you know that I'm moving to Transifex as the main platform for the translation workflow. 

You can join here: https://www.transifex.com/rafaelmardojai/blanket/.

I still will be accepting translations through GitHub if some of you prefer that workflow.

CC: @fitojb @juxuanu @pervoj @eladyn @Porrumentzio @mskf1383  @heidiwenger  @julroy67 @Moilleadoir @frandieguez @milotype @osiixy  @cho2   @albanobattistella @OctopusET @IBA4  @Vistaus @Mejans  @JulianoSCbah @hugok79 @pedrofleck @LeftyDeMilo @MartinIIOT @kostich @eson57 @123survesh @caglarturali @IhorHordiichuk @apocelipes

**Comment by milotype** [comment]
I'm a bit dissapointed that you chose Transifex over Weblate, as IMO, Weblate is better ...

**Comment by rafaelmardojai** [comment]
> I'm a bit dissapointed that you chose Transifex over Weblate, as IMO, Weblate is better ...

We use Weblate for [Dialect](https://github.com/dialect-app/dialect), and was my first option, but their free plan only allows you to own one project. I have seen some people creating a general project in Weblate and creating components for their different apps, but looks confusing and not ideal to me, and also I don´t want to create another account to do that.

So I ended testing the different alternatives out there (Transifex, POEditor, etc), and Transifex was the one I liked the most, it has a nice Github integration, intuitive interface and the most important part, it allows me to have unlimited open source projects  (I already have three apps apart from Dialect published, and a few more to come, so is really nice).

**Comment by Vistaus** [comment]
As a translator, I also like Transifex somewhat better than Weblate. Don't get me wrong: Weblate is pretty good, but not as good as Transifex, IMHO.

**Comment by rafaelmardojai** [comment]
> What other projects have you published on Transifex? Would love to help out on those projects as well (if I haven't already). :)

Webfont Kit Generator and Share preview (I think you already contributed to them), all of them are available in my Transifex org: https://www.transifex.com/rafaelmardojai/public/

**Comment by Vistaus** [comment]
> Webfont Kit Generator and Share preview (I think you already contributed to them), all of them are available in my Transifex org: https://www.transifex.com/rafaelmardojai/public/

Thanks! I indeed contributed to them already and just now I joined the resp. Dutch teams on Transifex as well. :)

**Comment by hugok79** [comment]
> > What other projects have you published on Transifex? Would love to help out on those projects as well (if I haven't already). :)
> 
> Webfont Kit Generator and Share preview (I think you already contributed to them), all of them are available in my Transifex org: https://www.transifex.com/rafaelmardojai/public/

I requested a new language **Portuguese (pt)** in transifex for this two,

**Comment by hugok79** [comment]
> Hey translators!
> 
> Just wanted to let you know that I'm moving to Transifex as the main platform for the translation workflow.
> 
> You can join here: https://www.transifex.com/rafaelmardojai/blanket/.
> 
> I still will be accepting translations through GitHub if some of you prefer that workflow.
> 
> CC: @fitojb @juxuanu @pervoj @eladyn @Porrumentzio @mskf1383 @heidiwenger @julroy67 @Moilleadoir @frandieguez @milotype @osiixy @cho2 @albanobattistella @OctopusET @IBA4 @Vistaus @Mejans @JulianoSCbah @hugok79 @pedrofleck @LeftyDeMilo @MartinIIOT @kostich @eson57 @123survesh @caglarturali @IhorHordiichuk @apocelipes

My profile in transifex, https://www.transifex.com/user/profile/hugok/ You can add me to the portuguese(pt) team.

**Comment by comradekingu** [comment]
@rafaelmardojai Happy to help if you use Weblate.
https://hosted.weblate.org/hosting/ only has restrictions on where the actual strings are stored.
https://weblate.bubu1.eu/ has no restrictions.
