### ISSUE TITLE
GstPlay is not specified as a dependency

### ISSUE THREAD

**Issue by milliams** [rafaelmardojai/blanket#261]
I'm running Blanket 0.6.0 installed from [RPM on openSUSE](https://build.opensuse.org/package/show/multimedia:apps/blanket). I believe that the build system there is able to automatically work out the required dependencies by looking at the registered plugins by `gi.require_version()` (using `pkgconfig(gobject-introspection-1.0)` I think).

Given the known issues, e.g. #199 you have updated blanket to support GStreamer 1.20 and the new `GstPlay` interface. However, the `require_version` line is still:
```
gi.require_version('GstPlayer', '1.0')
```
This seems to be causing the RPM to only define a dependency on:
```
Requires       : [9]
    /usr/bin/python3
    typelib(GLib)
    typelib(GObject)
    typelib(Gio)
    typelib(Gst) = 1.0
    typelib(Gdk) = 4.0
    typelib(Gtk) = 4.0
    typelib(Adw) = 1
    typelib(GstPlayer) = 1.0
```
and so it does not install the `GstPlay` library and so it falls back to the `GstPlayer` path which fails as in #199

Maybe it makes sense to update the `require_version` for `Gst` to `1.20` and to change `GstPlayer` to `GstPlay`? I don't know enough about GObject etc to be sure.

**Comment by rafaelmardojai** [comment]
The main reason of the current state is that `1.20` wasn't available in the Flatpak Freedesktop platform (haven't checked if it's already available). So requiring `GstPlay` would make the app fail if `1.20` isn't installed.
