### ISSUE TITLE
Sounds not showing in Ubuntu 22.04

### ISSUE THREAD

**Issue by MilkAndBanana01** [rafaelmardojai/blanket#265]
![image](https://user-images.githubusercontent.com/94128784/183391530-d93fcace-de32-466a-ba1c-a17cc4b91056.png)
Installed from flatpak

**Comment by apandada1** [comment]
Can you check whether the PPA version helps? I tested it on Mint 21, which is based on Ubuntu 22.04

**Comment by rafaelmardojai** [comment]
@MilkAndBanana01 Does it print something when ran in the console? `flatpak run com.rafaelmardojai.Blanket `

**Comment by MilkAndBanana01** [comment]
Forgot about this. Apparently it has been fixed by a quick restart. Weird fluke I guess.
