### ISSUE TITLE
Menu to change app language

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#28]
Sometimes users want to use the app in other language than their local. A menu to choose the language could be good.

**Comment by rafaelmardojai** [comment]
I'm not sure about this. I want the user interface to be as simple as possible.

Also this isn't a feature that many people will use.

But I can implement a hidden setting than can be changed from terminal or dconf editor:
```bash
gsettings set com.rafaelmardojai.Blanket language "lang_iso"
```

**Comment by Porrumentzio** [comment]
That's good, it's okay to keep it simple. 

I understand that what I propose wouldn't be very used. The problem is that some locales, Esperanto for example, is so little translated that almost all the apps are in English; then, there's no comfortable way to use apps in Esperanto unless each app allows to choose the language.

**Comment by fitojb** [comment]
On Linux, you can start most apps in a different language by using the LANG= environment variable, e.g. `LANG=ca libreoffice`

**Comment by Porrumentzio** [comment]
You can, but it's not comfortable having to launc the app every time via terminal.

I already explained the reasons to such menu and that I understand and respect the aim to keep the app simple.

**Comment by pedrofleck** [comment]
> You can, but it's not comfortable having to launc the app every time via terminal.
> 
> I already explained the reasons to such menu and that I understand and respect the aim to keep the app simple.

You can edit you .desktop file and it will always launch with your desired language, unless you want different languages from time to time.
