### ISSUE TITLE
Creating new preset shouldn't clear the current selection

### ISSUE THREAD

**Issue by lig** [rafaelmardojai/blanket#280]
Steps:
- Open app
- Select some sounds combination
- Open menu and select Presets > Add Preset...

Actual result:
- New preset created
- All sound selections are cleared

Expected result:
- New preset created
- All previously selected sounds are copied into the newly created template

**Comment by rafaelmardojai** [comment]
The new presets implementation now behaves like this.

**Comment by lig** [comment]
Thanks! I'll give it another try:)

**Comment by rafaelmardojai** [comment]
> Thanks! I'll give it another try:)

It's on the master version right now.
