### ISSUE TITLE
Merge audio file format filters in file chooser 

### ISSUE THREAD

**Issue by gregorni** [rafaelmardojai/blanket#287]
The file chooser for adding a custom sound doesn't show any files, only directories.

**Comment by PrathamBhatTech** [comment]
Have the same issue

**Comment by rafaelmardojai** [comment]
Hmm, that's weird, have you tried changing the filter to match your audio file format?
![Captura desde 2022-12-15 11-47-17](https://user-images.githubusercontent.com/6210397/207919209-99627bea-d1a4-49a2-a938-b9cd79bade3d.png)

**Comment by gregorni** [comment]
Crazy, that seems to have solved it. But don't you think having that filter is kind of unintuitive? I think it would be better if the file chooser would simply display all audio files.

**Comment by rafaelmardojai** [comment]
> Crazy, that seems to have solved it. But don't you think having that filter is kind of unintuitive? I think it would be better if the file chooser would simply display all audio files.

Yeah true, I might do a "Audio files" unique filter with all the supported formats.
