### ISSUE TITLE
Can we get a Windows version?

### ISSUE THREAD

**Issue by realKarthikNair** [rafaelmardojai/blanket#293]
I'm an avid Linux user but I would really love to recommend Blanket app to my friends (who statistically are Windows users) without forcing them to switch their entire workflow to Linux.

I don't have the knowledge to package it for Windows right now, plus I've already seen a similar issue closed with the `wontfix` tag.

**It would be really appreciated if you could add the `Help Needed` tag to this issue and pin it so that anyone else who is able to do the same can contribute Windows packages**

No matter what, ~75% desktop userbase is Windows and Blanket is a really good program with a clean GUI

**Comment by HongYue1** [comment]
I also want this.

**Comment by github-user93** [comment]
while searching for something similar. i came across this website that works pretty similarly.
https://asoftmurmur.com/

after installing it as a chrome pwa, it seems to work pretty well.

**Comment by Tlamatinime** [comment]
Ambie might also be an option for your friends [Github](https://github.com/jenius-apps/ambie), [website](https://ambieapp.com/).

**Comment by realKarthikNair** [comment]
@Tlamatinime perfect. Thanks.
