### ISSUE TITLE
[Request] Update Blanket to support new Adw.AboutWindow

### ISSUE THREAD

**Issue by Scotty-Trees** [rafaelmardojai/blanket#296]
All new GTK4/libadwaita applications over the last year have made great progress porting and updating components to support the latest and greatest of the Gnome stack. I noticed that Blanket is still using the old version of the "About" window and would love to see if it can be updated to support the new Adw.AboutWindow as seen below for reference:

https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.AboutWindow.html

Edit: For context here is an image of the old About Window vs the new Adw.AboutWindow:

[OLD]
![Screenshot from 2023-02-20 13-20-15](https://user-images.githubusercontent.com/45135187/220177285-c3c2e5cb-7a0c-49c4-9e68-7c9dea19c059.png)

[NEW]
![Screenshot from 2023-02-20 13-20-48](https://user-images.githubusercontent.com/45135187/220177344-e92c9508-d85b-4efe-877a-2c41efd9d185.png)

Feel free to let me know if this is already planned or upcoming in a new release, thank you.

**Comment by rafaelmardojai** [comment]
This was already done in October [b049dcb6675aaebbbe89faacb27d20698d0a8244]. I just need to finish others things before releasing.

**Comment by Scotty-Trees** [comment]
Awesome, this is very good news to hear! And thank you for the quick reply. I look forward to the next release, take all the time you need. I use Blanket mostly when I am out to give my dog a nice relaxing atmosphere while I am away, so I use it quite often, so thank you again for your continued work.
