### ISSUE TITLE
Pink Noise Loop Gap

### ISSUE THREAD

**Issue by har-nick** [rafaelmardojai/blanket#298]
Hi! Love the app, just wanted to let you know the Pink Noise SFX has a noticeable gap when the the track loops.

**Comment by haggen88** [comment]
@har-nick / @rafaelmardojai maybe this will fix it:
 [data_resources_sounds_pink-noise_.ogg.zip](https://github.com/rafaelmardojai/blanket/files/11360563/data_resources_sounds_pink-noise_.ogg.zip)
