### ISSUE TITLE
MPRIS control: It seems Blanket doesn't know the methods Pause, Play, and Stop; only Play-Pause

### ISSUE THREAD

**Issue by lstrtstr** [rafaelmardojai/blanket#316]
According to my GDBus output, Blanket doesn't know the method Pause. This causes playerctl to fail when Blanket is active (and not ignored explicitly), so it's not possible to pause all MPRIS-capable players while Blanket is running, only toggling them (and some might be paused while others might be playing).

These fail:
```
$ playerctl --all-players pause
Could not execute command: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Pause”

$ playerctl --all-players stop
Could not execute command: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Stop”

$ playerctl --all-players play
Could not execute command: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Play”
```

While these work:
```
$ playerctl --all-players play-pause
$ playerctl --all-players --ignore-player=Blanket pause
$ playerctl --all-players --ignore-player=Blanket play
$ playerctl --all-players --ignore-player=Blanket stop
```

Please add these methods, especially Pause. Thanks!

**Comment by rafaelmardojai** [comment]
Thanks for the report.

Pause and Play were added almost a year ago in #276.

I can also implement Stop, should be trivial.
