### ISSUE TITLE
Blanket 0.7 works very well with touch screen

### ISSUE THREAD

**Issue by archisman-panigrahi** [rafaelmardojai/blanket#340]
(This is not an issue but feedback)

I recently used blanket 0.7.0 on a touch screen laptop (Kubuntu 24.04+Wayland+Blanket as PPA), and it works really well.
Scrolling up and down, and changing the volume individual sounds works in the same smooth way as in Android apps in phones.

Thank you very much for creating and maintaining blanket, and congratulations on this new release.

**Comment by rafaelmardojai** [comment]
Thanks! Good to know it works good. I made the volume vars a bit more taller thinking on touch devices, so glad that it helped.
