### ISSUE TITLE
uses slightly more cpu than other audio players

### ISSUE THREAD

**Issue by userforsource** [rafaelmardojai/blanket#342]
Don't know why but it uses more cpu in system
As compare to other music player hence i recommend to make it use less cpu as cpu is important cor laptops which are running on battery.

**Comment by rafaelmardojai** [comment]
Duplicated of #314.

Blanket has the limitation of using a player object per sound, so it uses more CPU than any other GStreamer (the multimedia library used by Blanket) application that only plays one track at a time.

This is planned to be improved by a rewrite of the playback code (#313) that is still a work in progress.
