### ISSUE TITLE
BUG: App exists with close button

### ISSUE THREAD

**Issue by tmdag** [rafaelmardojai/blanket#353]
There is currently no way (Or I just don't know how) to minimise app to the tray icon. When I click top right window close button, app exits, instead of minimising and running in the background.

Tested on Fedora 39

**Comment by rafaelmardojai** [comment]
In the app's main menu there's a "Keep Playing when Closed" item you can activate.

**Comment by tmdag** [comment]
Oh yeah, thank you, missed it. Was initially looking to this setting in preferences. My bad.
