### ISSUE TITLE
BUG: App requires manually setting each sound's volume away from zero. 

### ISSUE THREAD

**Issue by calliereimann** [rafaelmardojai/blanket#357]
System: Linux Mint 21.3 Cinnamon 6.0.4
App Version: 0.7.0 Flatpak 

Whenever the Blanket app is started, it creates the sound channels for each of the sounds that are meant to be playing, but it sets all of their volumes to 0. In order to receive audio playback, I have to open Sound Settings and manually change each sound's volume from 0 to its desired value, then pause the sounds and hit play again, every single time I start up Blanket. This is vaguely tolerable when I only want to listen to four or five sounds, but complex sound mixes require upwards of 20 clicks, and more than that, there's no saving of sound preferences because the values I set it to in the sound settings override the slider bars in the Blanket app, rather than working alongside them - setting everything to 100 just makes everything maximum value, instead of accurately balancing based on what the in-app sliders say. 

Here is an example of the sounds settings menu, immediately after starting Blanket up. 
![image](https://github.com/rafaelmardojai/blanket/assets/70546246/c2b40a7e-fe72-4e44-a280-da7a12f44ca6)

This bug did not occur prior to the most recent version, and has occurred consistently since then.

**Comment by calliereimann** [comment]
I can no longer reproduce this bug on the same machine it was previously occurring on, even in as close to the same circumstances as it was previously.

**Comment by rafaelmardojai** [comment]
Yes, I've seen this happen a few times, but can't tell the cause, but it's definitely external to Blanket.
