### ISSUE TITLE
Feature request: minimize to system tray in Ubuntu Wayland

### ISSUE THREAD

**Issue by c-vigo** [rafaelmardojai/blanket#359]
It would be very convenient to minimize the app to the system tray when closing

**Comment by rafaelmardojai** [comment]
The app can be closed to run in the background and be activated with the MPRIS integration (media player notification). So IMO a system trayis out of scope.

**Comment by Iss-in** [comment]
I think a tray icon would be useful in knowing when app is running and when not, which can be really inconvenient to find out in low sound. especially when it interferes with other media.

as for mpris controls, those are limited to gnome and kde, but not window managers. so no way to control it in them

**Comment by rafaelmardojai** [comment]
> as for mpris controls, those are limited to gnome and kde, but not window managers. so no way to control it in them

I guess that could be a nice opportunity for project of a mpris controller implemented with appindicator, that way you could get access to every app implementing mpris in any window manager.
