### ISSUE TITLE
Integrate Blanket Play/Pause into Gnome

### ISSUE THREAD

**Issue by nicolae-stroncea** [rafaelmardojai/blanket#42]
Thanks for creating a fantastic offline background noise app! It's great to set it and forget it, and not worry about ads, logging into anything, internet connection timing out or accidentally closing the tab.

I'm using the Blanket Flatpak on Fedora Gnome 3.36 and it would be great to be able to control it from keyboard, mainly I'd love to be able to pause it/resume it by using my keyboard shortcuts for Sound and Media.

**Comment by rafaelmardojai** [comment]
Latest version provides MPRIS integration. So that is already possible.

You should be able to control it from the GNOME notifications panel or with keyboard media keys if there isn't other media player interfering.

**Comment by nicolae-stroncea** [comment]
You're right, I was using multiple media players which is what caused Blanket not to respond
