### ISSUE TITLE
[Idea] Add new sounds

### ISSUE THREAD

**Issue by haggen88** [rafaelmardojai/blanket#46]
I recently discovered Blanket. I think it is a very interesting app and perhaps the sound catalog could be expanded by including things like: 
-sound of waves
-sound of birds 
-sound train 
[as in [asoftmurmur](https://asoftmurmur.com) / [noisli](https://www.noisli.com) / [ambient-mixer](https://www.ambient-mixer.com) ]

PS: Have you thought about improving the sound of Rain a little more? It usually looks more like a stream.

**Comment by rafaelmardojai** [comment]
Before adding new sounds we should resolve #20 first. But i agree, those three would be nice additions.

**Comment by Porrumentzio** [comment]
Hi @haggen88! I totally agree with those sounds.

As noted at the end of #20, I proposed some specifications all sounds should have to be comfortable. I'm ready to have a hear to new sounds to make them more comfortable.
Do you have any concrete soundclip? Would they be downloaded from the internet or recorded?

**Comment by haggen88** [comment]
- For **waves** I can think of something like:
https://freesound.org/people/Luftrum/sounds/48412/
or one of calm sea and soft waves from here
https://www.soundsnap.com/search/audio/waves/score

- For the **train** I imagine a soothing sound from the wheels. Something similar could be:
https://freesound.org/people/SDLx/sounds/259988/
https://freesound.org/people/YOH/sounds/170866/
https://www.soundsnap.com/search/audio/Freight%20train%20passes%20at%20slow%20speed%20with%20scraping%20and%20squeaking%20of%20wheels%20on%20track/score

- For **bird** sounds you could even look for a sound clip combination:
https://freesound.org/people/kvgarlic/sounds/188812/
https://freesound.org/people/HerbertBoland/sounds/28239/
https://freesound.org/people/kvgarlic/sounds/156826/

--
Ambient-mixer allows you to create scenarios using various sound clips. From here I take some references:
https://harry-potter-sounds.ambient-mixer.com/storm-on-the-hogwarts-express
https://relaxing.ambient-mixer.com/on-a-ship-at-sea
https://wild-life.ambient-mixer.com/birds-in-a-field

**Comment by Porrumentzio** [comment]
I'll analyze them some hours after. Are they all of free use?

**Comment by haggen88** [comment]
> I'll analyze them some hours after. Are they all of free use?

- [soundsnap](https://www.soundsnap.com/licence) licence // FAQ: [Legal](https://soundsnap.zendesk.com/hc/en-us/articles/115003916431)
- [freesound](https://freesound.org/forum/legal-help-and-attribution-questions/38292/) use Creative Commons variants [audio clips must be reviewed individually]

**Comment by Porrumentzio** [comment]
Okay, so with licenses we won't have problems if saying the _author_ (done since now in Blanket).
I'll analyze those audios

**Comment by Porrumentzio** [comment]
We won't have problems with those licenses, as Blanket is already saying the _authory_ of sounds.

I'll choose the more comfortable clips for me and adequate them to fit into the recommendations!

**Comment by Porrumentzio** [comment]
I did not find any suitable and free soundclip for Train. I successfully modified the other three!

**Comment by haggen88** [comment]
> I did not find any suitable and free soundclip for Train. I successfully modified the other three!

At the moment I am looking for clips more suitable for the sound of the train, something like this:
-https://podcast.ausha.co/asmr/relaxing-train-journey
-https://www.youtube.com/watch?v=4mFMXRWWffw

Something from inside the train where a subtle and periodic sound of the wheels can be perceived.

**Comment by Porrumentzio** [comment]
I downloaded, trimmed and analyzed the first audio (that from YouTube has copyright) and although I like its sound, that is what you described, I has a very low range. Due to that I think that it won't be comfortable for listening to it on long time.

This, for sure, is arguable, this is very subjective :smile: 
Thanks for your proposals @haggen88, they are very interesting, I'll try to fit the train sound :)

**Comment by haggen88** [comment]
@Porrumentzio   I found audios that may interest you. Both are licensed [Creative Commons Sampling Plus 1.0](https://creativecommons.org/licenses/sampling+/1.0/). It is a license that is no longer promoted ([was retired](https://creativecommons.org/2011/09/12/celebrating-freesound-2-0-retiring-sampling-licenses/)) ... but since CC licences are [irrevocable](https://creativecommons.org/faq/#what-happens-if-the-author-decides-to-revoke-the-cc-license-to-material-i-am-using), they must be used as they are.
- train by vahid [from https://trains.ambient-mixer.com/rainy-train]:
[Train by Vahid _Creative Commons Sampling Plus 1.0 License.ogg.zip](https://github.com/rafaelmardojai/blanket/files/5249634/Train.by.Vahid._Creative.Commons.Sampling.Plus.1.0.License.ogg.zip)

- train wheels by funsoundtube [from https://trains.ambient-mixer.com/long--sleepy-train-ride]
[t2 - train wheels by funsoundtube _Creative Commons Sampling Plus 1.0 License.ogg.zip](https://github.com/rafaelmardojai/blanket/files/5249641/t2.-.train.wheels.by.funsoundtube._Creative.Commons.Sampling.Plus.1.0.License.ogg.zip)

---

I also found other sound clips that might work: 
- https://freesound.org/people/jrosin/sounds/209972/           [CC0 1.0]
- https://freesound.org/people/ftpaddict/sounds/180318/      [CC BY 3.0]
- https://freesound.org/people/allh/sounds/133099/              [CC0 1.0]
- https://freesound.org/people/Geissler/sounds/69593/        [CC BY 3.0]

**Comment by Porrumentzio** [comment]
Hey, what a great work! Thanks for explaining the license, and you know what? The first clip is simply perfect!
I'll add it :)

**Comment by haggen88** [comment]
@Porrumentzio  Great!. 
Since the current sound of rain will be improved, I would not like that sensation of moving water to be lost.
Would it be possible to add something like a stream ?. Here are some examples:

-https://freesound.org/people/INNORECORDS/sounds/469009/   [CC0 1.0]
-https://freesound.org/people/gluckose/sounds/333987/                [CC0 1.0]

**Comment by Porrumentzio** [comment]
I analyzed them and they have an extremely tiny range, what is completely natural being a stream. If we add that sound, it should be on low volume, but I think it won't be very comfortable (it's very _repetitive_)

What do you think about that? Maybe also is me, that I'm more sensible to the range than others (this is very probable 😅)

**Comment by rafaelmardojai** [comment]
Yeah, is very repetitive, but I think someone who wants to hear to a stream wouldn't be disappointed since is how is supposed to sound.

**Comment by Porrumentzio** [comment]
For sure: some sounds are repetitive and monotonous and that's not bad. So lets add it?

**Comment by haggen88** [comment]
@Porrumentzio     Personally, I especially like it when combined with the sound of the birds, I leave it up to you.

**Comment by Porrumentzio** [comment]
Done #52
