### ISSUE TITLE
Remove saving window scroll position during scrolling

### ISSUE THREAD

**Issue by RedGradient** [rafaelmardojai/blanket#47]
Scrolling is laggy as the Blanket writes the window scroll position to disk directly during scrolling. It also makes my HDD make noise  (this is what prompted me to write an issue in the first place).

**Comment by rafaelmardojai** [comment]
Now I'm binding the scroll with gsettings, could you test if this solve the issue? 

Otherwise, I'm going to implement a more performant approach.

**Comment by RedGradient** [comment]
Nothing has changed. The program behavior is the same.
Version: 0.3.1.r6.g2d80889

**Comment by rafaelmardojai** [comment]
Right. I will implement some logic to improve this.

**Comment by rafaelmardojai** [comment]
I have implemented smart scroll saving. Could you test if still lags for you?

**Comment by RedGradient** [comment]
There is no lags anymore. However, saving may not occur if less than a second has elapsed between changing the scroll and closing the window. You can set a smaller timeout, but why not just do the save when closing the window? The same approach can be applied to saving volume scrolls' position, which will drastically reduce the number of I/O operations.

**Comment by rafaelmardojai** [comment]
That was my first idea, but constant electrical cuts where I live made me implement it in this way.

However, I agree about saving on close would be better. I will try to figure out a better approach, otherwise I will implement the save when closing the window.
