### ISSUE TITLE
4.0 Sounds 

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/blanket#50]
### New sounds

**Nature**
- [x] Waves (#48)
- [x] Birds (#48)
- [x] Stream (#52)

**Travel**
- [x] Train (#51)
- [x] Boat (#55)
- [x] City (#55)

**Noise**
- [ ] Brown (Red) Noise

### Icons

- [ ] Waves
- [ ] Birds
- [ ] Stream
- [ ] Train
- [ ] Boat
- [ ] City
- [ ] Brown Noise

### Sound improvements
- [x] Rain (#48)
- [x] Storm (#48)
- [ ] Wind
- [ ] Summer Night
- [ ] Coffee Shop
- [ ] Fireplace
- [ ] Pink noise (should be fixed with #11)
- [ ] White noise (should be fixed with #11)

**Comment by rafaelmardojai** [comment]
cc @Porrumentzio

**Comment by rafaelmardojai** [comment]
@Porrumentzio any suggestions on what category use for Train? Should we change nature/interiors to outdoors/indoors?

**Comment by Porrumentzio** [comment]
I think `Nature` will be more understandable than outdoors, so I would let it that way. I think we could add some category such as `Civilized` or something that way, to say that it has been changed by humans, but `Coffee Shop` is ambiguous between `Interiors` and `Civilized`

What do you think? And @haggen88?

**Comment by rafaelmardojai** [comment]
What about `Civilization`?  And `Fireplace` could go in there since is a civilized fire? 🤣

**Comment by haggen88** [comment]
IMHO the train sound is recorded from inside the locomotive, even though it is moving outside [it is not a passing train].
It is necessary to see which criterion has more weight to define the sounds.
ex. They can be defined according to: 
A) who / what produces them [natural / artificial-human] 
B) the distance from the emitting source [near / interior - far / exterior].

**Comment by Porrumentzio** [comment]
Could be :laughing: Doesn't uncivilized cultures make fire? Or is it so clear that that fire is in a chimney fireplace?

**Comment by Porrumentzio** [comment]
I think that is more understandable to have an object-centred view of sounds, because our minds in current culture thought that way, not depending on the subject.
So I think that option A, sound source, will be more comprehensible.

**Comment by haggen88** [comment]
@Porrumentzio @rafaelmardojai 

What is civilized or uncivilized is more complex [depending on who defines the level of culture]. Perhaps another selection criterion could be according to the mobility of the environment [static - in transit].

Perhaps a category of traffic / travel is easier to understand. Maybe in the future more sounds can be added such as boat or car travel [or car traffic / soft city noise]

-https://freesound.org/people/Falcet/sounds/439365/
-https://freesound.org/people/Pfannkuchn/sounds/360630/
-https://freesound.org/people/priesjensen/sounds/495795/
-https://freesound.org/people/adejabor/sounds/153442/
-https://freesound.org/people/ramagochi/sounds/523843/

**Comment by Porrumentzio** [comment]
That's good. Something as Travel or Transport would be good I think

**Comment by Porrumentzio** [comment]
What about writing down somewhere the possible future sounds? That way we could add them by groups and more organizedly

**Comment by rafaelmardojai** [comment]
> Perhaps a category of in transit/travel is easier to understand. Maybe in the future more sounds can be added such as boat or car travel [or car traffic / soft city noise].

Yeah, that looks good.

But, what I don't want is the sound catalog to be very large. Currently we have 9 sounds (removing noise sounds that will be generated) witch are `13,5 Mb`. We need to put a limit on how much this could grow.

Probably later we can create an extended online catalog of curated sounds, and users can download those sounds inside the app.

**Comment by Porrumentzio** [comment]
It has something to see the length of files. Does the app cycle through all the length of each file or does only take a piece of it? 

If the second case, the sound comfortability will decrease but the files could be cut.

**Comment by rafaelmardojai** [comment]
> It has something to see the length of files. Does the app cycle through all the length of each file or does only take a piece of it?

The app loop the whole audio file.

**Comment by Porrumentzio** [comment]
Okay, so it would be good to put a limit of disk, although I don't really understand the reason.

Other possibility would be to work with plugin-packages: `travel-sounds-blanket`, `nature-sounds-blanket` and so on. This way the main app would be lightweight but it would be easy to add more sounds (an announcement about this in the app would be great for users)

**Comment by haggen88** [comment]
> 
> Yeah, that looks good.
> 
> But, what I don't want is the sound catalog to be very large. Currently we have 9 sounds (removing noise sounds that will be generated) witch are `13,5 Mb`. We need to put a limit on how much this could grow.
> 
> Probably later we can create an extended online catalog of curated sounds, and users can download those sounds inside the app.

Personally to this new category I would leave it with 3 sounds:
-train [done]**
-boat
-light traffic / street sounds

**Comment by rafaelmardojai** [comment]
> - boat: Ambience Sea Boat Night Ropes - 1 and 4.zip
> - light traffic / street sounds: ny streets.zip

I'm fine about adding those. We don't want the new `Transport` category to have one sound.

> Okay, so it would be good to put a limit of disk, although I don't really understand the reason.

I just don't want to bloat users with a lot of sounds that they are not going to use. We should ship the sounds that people expect in this kind of program.

> Other possibility would be to work with plugin-packages: travel-sounds-blanket, nature-sounds-blanket and so on. This way the main app would be lightweight but it would be easy to add more sounds (an announcement about this in the app would be great for users)

Yeah, that is another option. But having an online catalog allows us to add new sounds without releasing new versions.

**Comment by Porrumentzio** [comment]
No matter the how, it's okay :)
I'll have a look to new sounds.

**Comment by haggen88** [comment]
I have a doubt ... does the reproduction of the current loop of the sounds have some kind of crosfade? Or are the sound clips edited in such a way as to make the sounds more "continuous" and without volume drops / silences?.

**Comment by Porrumentzio** [comment]
They have not such a think AFAIK. Most sounds coincide that the beginning and ending are similar and match. I'm just gonna change the new rain clip because the loop limit is noticeable.

Do you dislike that?

**Comment by rafaelmardojai** [comment]
`light traffic / street sounds` could be named `City Trafic` or simply `Street`.

> I have a doubt ... does the reproduction of the current loop of the sounds have some kind of crosfade? Or are the sound clips edited in such a way as to make the sounds more "continuous" and without volume drops / silences?.

When I created the app, edited some sounds to avoid gaps when looping.

**Comment by Porrumentzio** [comment]
By the way, @haggen88, could you add the links to those new transport sounds please?

**Comment by haggen88** [comment]
> By the way, @haggen88, could you add the links to those new transport sounds please?


- https://freesound.org/people/Falcet/sounds/439365/  >  Ambience_Sea_Boat_Night_Ropes_4 / [CC0 1.0]
- https://freesound.org/people/Falcet/sounds/439368/ >  Ambience_Sea_Boat_Night_Ropes_1 / [CC0 1.0]

- https://freesound.org/people/gezortenplotz/sounds/44796/   > NY Streets / [CC BY 3.0]

**Comment by Porrumentzio** [comment]
Thanks for the links @haggen88! The clips are edited to fit in the loop.

@rafaelmardojai, what about `City` for the NY street sound?

**Comment by rafaelmardojai** [comment]
> what about City for the NY street sound?

`City` and `Street` fits perfect for that sound. But I prefer to `Street` as personal taste.

**Comment by Porrumentzio** [comment]
It doesn't really matter to me. For me City is more accurate, because the streets on my tiny village doesn't sound that way, but only those of cities 😅🤣

**Comment by rafaelmardojai** [comment]
You got a point. Let's go with `City`.

**Comment by rafaelmardojai** [comment]
Just added the new sounds to the UI. Just need to get some free time to work on icons.

**Comment by Porrumentzio** [comment]
I'm testing them. Test by yourself too and say if the level is okay. Seems to me that the volume is maybe a bit low, but maybe that's because before they were too loud.

**Comment by rafaelmardojai** [comment]
Overall sounds good to me. 

The only detail is that the new rain is too soft for what I'm used 😅️, but not a real issue.

**Comment by Porrumentzio** [comment]
It's possible that it's due to the new has a greater range (the perception is a lower volume). We'll have to test and test since have a good level of each sound, this is more a subjective issue than a mathematic.

So use it more and if in three days of use it's still too low, I'll change it :)

**Comment by rafaelmardojai** [comment]
> It's possible that it's due to the new has a greater range (the perception is a lower volume). We'll have to test and test since have a good level of each sound, this is more a subjective issue than a mathematic.

Technically is fine. The issue is that I live in rain forest, and rain sometimes doesn't sounds like that 😂

**Comment by Porrumentzio** [comment]
We should so name that sound as "Non-rainforest Rain" 😉

**Comment by haggen88** [comment]
The sound concept of rain varies according to the experience given by the place where you live. I don't think there can be such a thing as a universal rain:
![output-1](https://user-images.githubusercontent.com/68134588/94470967-c797b180-019e-11eb-88f3-b1a98aedeb7a.png)

BTW here are some [concepts.zip](https://github.com/rafaelmardojai/blanket/files/5294281/concepts.zip) for the icons ... maybe they can be useful

---

P.S.  If Blanket is able to expand the catalog or work with "add-on packages" in the future, I suggest a couple of clips as a concept:

- cat:   https://freesound.org/people/16H_Panska_Rudenko_Angelika/sounds/499366/     [CC0 1.0]
- frogs_1  https://freesound.org/people/nebyoolae/sounds/209609/ [CC BY 3.0]
- frogs_2  https://freesound.org/people/LukeIRL/sounds/176124/    [CC BY 3.0
- frogs_3   https://freesound.org/people/eastierp/sounds/191016/  [CC BY-NC 3.0]

**Comment by CharoSW** [comment]
Would it be possible to add Brown noise along side the Pink and White noise?
