### ISSUE TITLE
No icon on Marco window manager [MATE]

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#54]
No matter if installed via AUR or compiled, Blanket does not have icon on Marco window manager, MATE.
![irudia](https://user-images.githubusercontent.com/61913683/93710476-70af2e00-fb47-11ea-825d-2617fe4deee7.png)
Happened on Manjaro MATE.

**Comment by rafaelmardojai** [comment]
Can you test if this commit fix the issue?

**Comment by Porrumentzio** [comment]
It doesn't

**Comment by rafaelmardojai** [comment]
Test again, [b3d0f92] should fix this.

**Comment by Porrumentzio** [comment]
Works!

**Comment by rafaelmardojai** [comment]
I commited [423097d] to use the symbolic icon instead because is displayed very small.

Could you confirm how it looks?

**Comment by Porrumentzio** [comment]
mmm
It worked, but it's worse now:
![irudia](https://user-images.githubusercontent.com/61913683/93719097-bd632b00-fb80-11ea-8b4c-918d3f73cb73.png)

A solution could be to add a white border to the icon

**Comment by rafaelmardojai** [comment]
Added a new icon with white border. How looks now?

**Comment by Porrumentzio** [comment]
Now it's better, although it looks a bit like 16-bit
![irudia](https://user-images.githubusercontent.com/61913683/93781849-1a66eb80-fc2a-11ea-9b13-c74d60a714af.png)

It's good like that 👍
