### ISSUE TITLE
Failure to run due to unsupported locale setting

### ISSUE THREAD

**Issue by psukys** [rafaelmardojai/blanket#56]
Hey, after installing on Fedora 32 and attempting to run, I got the following error (application didn't continue)

```
$ flatpak run com.rafaelmardojai.Blanket
Traceback (most recent call last):
  File "/app/bin/blanket", line 39, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by apandada1** [comment]
Does this help? https://stackoverflow.com/a/36257050/3128341

Someone commented that the debian specific last command was not required.

**Comment by rafaelmardojai** [comment]
@psukys Could you test current git master?

**Comment by psukys** [comment]
@apandada1 this does help (and indeed `dpkg` is not by default on Fedora), any specifics - why?

@rafaelmardojai attempted to manually build and run, but failed:
```
Traceback (most recent call last):
  File "/usr/local/bin/blanket", line 47, in <module>
    from blanket import main
  File "/usr/local/share/blanket/blanket/main.py", line 25, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1
```

**Comment by rafaelmardojai** [comment]
> @apandada1 this does help (and indeed dpkg is not by default on Fedora), any specifics - why?

I'm also running Fedora 32 with the `LC_ALL` empty and, never got this error.

This  was also reported here: https://github.com/flathub/com.rafaelmardojai.Blanket/issues/4. And should be fixed in current master.

Could you download the flatpak attached on that issue?

**Comment by psukys** [comment]
@rafaelmardojai tried the attached flatpak, works well. Probably related log message that covers the empty locale
```
(blanket:2): Gtk-WARNING **: 09:26:13.341: Locale not supported by C library.
	Using the fallback 'C' locale.
```

**Comment by apandada1** [comment]
@psukys the error when to tried to run blanket from source implies you will have to install version 1 of `libhandy` (using rpm).

**Comment by rafaelmardojai** [comment]
> @rafaelmardojai tried the attached flatpak, works well. Probably related log message that covers the empty locale

Yeah, the local issue is still there, but at least the app will launch. 

Out of curiosity, what is your `locale` output?

**Comment by psukys** [comment]
nothing too out of the ordinary, I suppose:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=lt_LT.UTF-8
LC_TIME=lt_LT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=lt_LT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=lt_LT.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=lt_LT.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

**Comment by WuerfelDev** [comment]
I just installed it from flathub and ran into the same problem. It works temporary by manually setting the LC_ALL. (But only if its started via command from the same terminal window)

**Comment by BrunoVernay** [comment]
Same on Fedora 33:
```
 flatpak run com.rafaelmardojai.Blanket
Traceback (most recent call last):
  File "/app/bin/blanket", line 39, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

```
locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
This works : `LC_ALL="en_US.UTF-8" flatpak run com.rafaelmardojai.Blanket`

**Comment by rafaelmardojai** [comment]
Could you test this flatpak? [com.rafaelmardojai.Blanket.zip](https://github.com/flathub/com.rafaelmardojai.Blanket/files/5229643/com.rafaelmardojai.Blanket.zip)

**Comment by BrunoVernay** [comment]
Just a warning, but works 0.3.1 seems OK

```
 flatpak run com.rafaelmardojai.Blanket

(blanket:2): Gtk-WARNING **: 19:56:03.455: Locale not supported by C library.
	Using the fallback 'C' locale.
```

**Comment by psukys** [comment]
Can't reproduce on 0.3.1
