### ISSUE TITLE
Blanket faders modify system fader upwards

### ISSUE THREAD

**Issue by Porrumentzio** [rafaelmardojai/blanket#57]
Changing the Blanket faders, both with mouse and with wheel, changes the general system sound level.
Tested in Manjaro MATE, both with JACK and PulseAudio.

_I also have the video file with sound if needed_
![Blanket-57-2020-09-21-165735](https://user-images.githubusercontent.com/61913683/93783512-0c19cf00-fc2c-11ea-8c39-00347d4db812.gif)

git version 2020/09/21 [9b99f1094e8de1aba1c25c9bd6aab99be105924f](https://github.com/rafaelmardojai/blanket/commit/9b99f1094e8de1aba1c25c9bd6aab99be105924f)

**Comment by rafaelmardojai** [comment]
This behaves as expected in my Fedora 32 setup.

![RecApp-2020-09-21-10:08:15](https://user-images.githubusercontent.com/6210397/93785385-a873af80-fbf3-11ea-80ae-f4d5c0a9d4b9.gif)
*Sorry for the shitty GIF conversion 😂*

**Comment by Porrumentzio** [comment]
Mmmm so maybe it's again the MPRIS integration on MATE?
If someone reading this and using MATE in other distro than Manjaro could test it would be great

**Comment by rafaelmardojai** [comment]
Not really related to MPRIS. Just related on how MATE/Manjaro handles sound.

**Comment by apandada1** [comment]
Works as expected with XFCE 4.14 in Xubuntu 20.04

**Comment by Porrumentzio** [comment]
I tested in Linux Mint with MATE and worked well. So probably it's a problem with Manjaro.

**Comment by apandada1** [comment]
@Porrumentzio Maybe, you can ask in the Manjaro Forums whether this is a known bug.

**Comment by Porrumentzio** [comment]
Done: https://forum.manjaro.org/t/app-fader-modifies-system-fader/29441?u=porru

Let's wait to someone's answer

**Comment by Porrumentzio** [comment]
So seems that it's my problem, due to having Jack installed I suppose.
Here's the answer on the forum.
