### ISSUE TITLE
New Option: Start Hidden in Background

### ISSUE THREAD

**Issue by sudoquai** [rafaelmardojai/blanket#65]
First of all:  I love Blanket - always searched something like that.

At the moment i am using Audacious with a Bird mp3 when my system boots, because it's able to start hidden (using the gnome media control for audacious so everything is pretty seemless)

Would it be possible to (auto) start Blanket, too ? Thx.

**Comment by rafaelmardojai** [comment]
I don't know how is the state of auto start in Flatpak. 

But for now a will add the `--hidden` flag to launch the app hidden.

**Comment by sudoquai** [comment]
Thank you very much @rafaelmardojai :+1:

**Comment by apandada1** [comment]
`blanket --hidden` works with the daily builds PPA as well.

**Comment by bilelmoussaoui** [comment]
> I don't know how is the state of auto start in Flatpak.
> 
> But for now a will add the `--hidden` flag to launch the app hidden.

Flatpak has a portal for autostart/running in the background.

**Comment by rafaelmardojai** [comment]
> Flatpak has a portal for autostart/running in the background.

You know what is the best way to implement this? I have to call `EnableAutostart` directly with D-Bus?

**Comment by bilelmoussaoui** [comment]
You need to use the RequestBackground dbus call https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-Background.RequestBackground. One thing to be aware of is that the portals waits for a user interaction (approval/or not of the interaction). The way it's handled is that each portal request, sends you an object path (mostly a dbus path) that you can call and wait for a response signal. The response contains the result of the interaction (whether the user approved it or not)

**Comment by rafaelmardojai** [comment]
> You need to use the RequestBackground dbus call https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-Background.RequestBackground. One thing to be aware of is that the portals waits for a user interaction (approval/or not of the interaction). The way it's handled is that each portal request, sends you an object path (mostly a dbus path) that you can call and wait for a response signal. The response contains the result of the interaction (whether the user approved it or not)

I see, I was looking to the wrong documentation.

You know if there are future plans to implement this at the toolkit level?

**Comment by rafaelmardojai** [comment]
> You need to use the RequestBackground dbus call https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-Background.RequestBackground. One thing to be aware of is that the portals waits for a user interaction (approval/or not of the interaction). The way it's handled is that each portal request, sends you an object path (mostly a dbus path) that you can call and wait for a response signal. The response contains the result of the interaction (whether the user approved it or not)

I see, I was looking to the wrong documentation.

You know if there are future plans to implement this at the toolkit level?
