### ISSUE TITLE
Scroll is broken when using touchpad

### ISSUE THREAD

**Issue by Skraylet** [rafaelmardojai/blanket#66]
OS: Fedora 32
Program version: 0.3.1 (from Flathub)

When scrolling with mouse everything works as expected. But with touchpad scroll position jumps either to the bottom or to the top.
You can see the problem in the attached GIF
![Screencast2](https://user-images.githubusercontent.com/26380693/96365503-b01e6980-1149-11eb-98c8-1def03cd0b42.gif)

**Comment by ilcaravaggio** [comment]
test if the problem also occurs with the rpm version:

https://copr.fedorainfracloud.org/coprs/tuxino/blanket/

(is building at the moment)

**Comment by Skraylet** [comment]
Tested. There is no such issue in the rpm version

**Comment by rafaelmardojai** [comment]
It's reproducible from other GNOME/Flathub apps? Or only Blanket if affected?

**Comment by Skraylet** [comment]
Most of apps installed on my system are flatpaks. And they behave correctly. I think it's Blanket specific bug.

**Comment by MichalLebeda** [comment]
Can confirm this with flatpak version installed

**Comment by Skraylet** [comment]
Issue is not present in 0.4.0
