### ISSUE TITLE
Small click sounds

### ISSUE THREAD

**Issue by MichalLebeda** [rafaelmardojai/blanket#67]
Hi, great app, but I have one problem. I hear small click/pause sometimes (I guess it's when the loop ends). Tried to play those ogg files in audacity, click is still there but much much smaller & less noticeable with pretty much no pause. I'm using flatpak version. Still great app but cannot use it right now as I have very sensitive ears.

**Comment by rafaelmardojai** [comment]
@Porrumentzio Can you reproduce this? 

I don't know if it's some performance issue with the loopping.

**Comment by Porrumentzio** [comment]
@MichalLebeda, could you specify in which soundclips you listen to those clicks and pauses most?

**Comment by MichalLebeda** [comment]
I think wind is pretty noticeable. Will post yt vid or something with marked clicks later. Btw are all the sounds playing with 0 volume or only those with volume > 0? It sounds like when I turn some clips volume to 0, and then raise volume again the play position is not the same

**Comment by rafaelmardojai** [comment]
The sounds are only played when volume > 0.

**Comment by rafaelmardojai** [comment]
@MichalLebeda have you tried building from source to test if the issue is present in current master?

**Comment by Porrumentzio** [comment]
I think that I know the reason for those clips. I'll try to solve this :)

**Comment by Porrumentzio** [comment]
Nope, I think it's an issue with how the program manages the loops, not the sounds. Looping it with other programs does not produce any click

**Comment by MichalLebeda** [comment]
So I found out I cannot record screen under wayland nor separate wayland window. Maybe I will use my phone when I have some time (school is much harder now). Will try current master and let you know

**Comment by MichalLebeda** [comment]
I can still hear click (on master build) especially when playing wind sample.

**Comment by rafaelmardojai** [comment]
Could try version `0.2.0` when building from source? Running `git checkout 0.2.0` in git clone.

That version had a different looping approach.

**Comment by MichalLebeda** [comment]
I think it sounds better! still hear small click but that could be the sample itself. I think that I don't hear any pause

**Comment by rafaelmardojai** [comment]
Ok, I'm going to re-implement that approach.

**Comment by rafaelmardojai** [comment]
> Could you try version 0.2.0 when building from source? Running git checkout 0.2.0 in git clone.

@Porrumentzio could you do the same and use the custom sound feature to test our new audios?

**Comment by rafaelmardojai** [comment]
Finally got time to work on this.

@MichalLebeda could you test the new looping method? Also probably the recent sounds makes the difference.

**Comment by MichalLebeda** [comment]
should I build it myself or use flatpak?

**Comment by rafaelmardojai** [comment]
You can build it, or [download the flatpak artifact](https://github.com/rafaelmardojai/blanket/suites/1675870909/artifacts/31304404) from the last commit.

**Comment by MichalLebeda** [comment]
It seems to be FIXED!!! Thanks for fixing the issue it is a really nice app

**Comment by MichalLebeda** [comment]
Maybe I didn't noticed before but now there is something strange (It may be present in previous version). It looks like turning volume up of some clip and then turning it completely off doesnt stop sound playing at volume 0.

![image](https://user-images.githubusercontent.com/5246963/103135990-bf2b1600-46bc-11eb-9500-afdca9bb4563.png)

**Comment by rafaelmardojai** [comment]
What do you mean? Sounds are paused when vol is 0 (That doesn't mean that it will disappear from GNOME Settings).

**Comment by MichalLebeda** [comment]
Ok, I think everything works well then
