### ISSUE TITLE
Provide missing graphics

### ISSUE THREAD

**Issue by jimmac** [rafaelmardojai/blanket#77]
I think the number of default sounds should be kept at a minimum. Currently the fold is somewhere at the 6 item mark. I would suggest de-emphasizing additional sounds by providing them in a more compact list below, perhaps using a symbolic icon or no icon at all. This would also help avoiding issues like [this one](https://github.com/rafaelmardojai/blanket/issues/64).

For now, Blanket should at least not present broken images, so it will need:

  * [ ] Waves
  * [ ] Stream
  * [ ] Birds

**Comment by jimmac** [comment]
Concept for the waves:
![image](https://user-images.githubusercontent.com/14821/101907486-eeb92900-3bba-11eb-827a-31e805e082fa.png)

**Comment by jimmac** [comment]
Stream is a little less successful for now...

![image](https://user-images.githubusercontent.com/14821/101911371-8d945400-3bc0-11eb-855b-d99e0835b7fb.jpeg)
![image](https://user-images.githubusercontent.com/14821/101911384-92f19e80-3bc0-11eb-8985-3d8cee5ab0f0.jpeg)

**Comment by rafaelmardojai** [comment]
Thanks for working on this!

We're also missing icons for Train, Boat and City (see #50).

> I would suggest de-emphasizing additional sounds by providing them in a more compact list below, perhaps using a symbolic icon or no icon at all. 

Yeah, definitely I will go that way.

**Comment by rafaelmardojai** [comment]
I really like the Waves concept. 

Both Stream concepts also look cool, and I can't decide 😂.

**Comment by jimmac** [comment]
Not quite the bird you'd like to fall asleep to:

![image](https://user-images.githubusercontent.com/14821/101928972-8a0bc780-3bd6-11eb-8ff4-0889ab9ce544.png)

**Comment by rafaelmardojai** [comment]
> Not quite the bird you'd like to fall asleep to:

But it fits with the geometric style 😅.

I like it, but what if it has a friend?

**Comment by jimmac** [comment]
While working on these, I've grown convinced that the fullcolor icon style is not appropriate for these. I think the symbolic icons would be more appropriate. If you're really into a larger illustration, I bet hairline/outline style would feel way more elegant.

**Comment by rafaelmardojai** [comment]
> While working on these, I've grown convinced that the fullcolor icon style is not appropriate for these. I think the symbolic icons would be more appropriate. If you're really into a larger illustration, I bet hairline/outline style would feel way more elegant.

Yes, you are right. And the outline style will help to have a bit more detail compared to a regular symbolic icon. 

My only concern is if this style will feel out of place in GNOME.

**Comment by jimmac** [comment]
There are always special cases. Considering these to be image assets (perhaps even animated) and not icons, I think it's a area where Blanket can be a great first test bed. There's some experimental [Lottie](https://airbnb.design/lottie/) support being worked on by the gtk developers, but for now I'll take a look at producing some 64x64px nominal static SVGs.

**Comment by haggen88** [comment]
some ideas... [concepts.zip](https://github.com/rafaelmardojai/blanket/files/5683125/concepts.zip)

**Comment by rafaelmardojai** [comment]
> There are always special cases. Considering these to be image assets (perhaps even animated) and not icons, I think it's a area where Blanket can be a great first test bed. There's some experimental Lottie support being worked on by the gtk developers, but for now I'll take a look at producing some 64x64px nominal static SVGs.

Go ahead, I think we can do something cool here. Definitely animated icons will look awesome in the future.

**Comment by jimmac** [comment]
The one thing before figuring out the animated icons might be to de-emphasize the inactive sound icons with something like `opacity: 0.8;`

**Comment by jimmac** [comment]
Alternatively having them blue when active would be better, but I'm not sure it's doable without duplicating assets.

**Comment by rafaelmardojai** [comment]
> Alternatively having them blue when active would be better, but I'm not sure it's doable without duplicating assets.

There's no way to make them "colorable" with CSS like normal symbolic icons? I suppose they can't because they are made with strokes.

**Comment by jimmac** [comment]
Strokes should be fine, worst case they can be converted to outlines. I'm not sure renaming to `-symbolic` will magically make it work though.

**Comment by apandada1** [comment]
Can we have the pastel effect (as in the attached images) instead of just the blue outline? It would look way cooler.
