### ISSUE TITLE
About button

### ISSUE THREAD

**Issue by Exalm** [rafaelmardojai/blanket#8]
Typically GNOME apps without a primary menu present about dialog like this:

![Screenshot from 2020-09-02 01-57-56](https://user-images.githubusercontent.com/1510457/91905298-c5395900-ecbf-11ea-9898-4e0bab7c5c31.png)

**Comment by bertob** [comment]
Personally I quite like the minimal icon-only treatment, I was wondering about maybe doing the same in Nostalgia too. Moving it to the left side could be nice for visual balance though.

**Comment by Exalm** [comment]
Well, it needs to be at least raised IMO, we normally don't use flat buttons like that.

**Comment by rafaelmardojai** [comment]
Blankek now has a menu. But I'm still interested in an "oficial" solution for  [Webfont Kit Generator](https://github.com/rafaelmardojai/WebfontKitGenerator).

![Captura de pantalla de 2020-09-04 11-41-28](https://user-images.githubusercontent.com/6210397/92264338-b6130080-eea3-11ea-945f-62ec26c3038d.png)
