### ISSUE TITLE
The golden moon icon (summer night) is too bright

### ISSUE THREAD

**Issue by apandada1** [rafaelmardojai/blanket#80]
The previous icon for summer night (silver moon with golden stars) was pleasing to look at.

The new icon seems to be too bright (it looks more like the sun than the moon), and somewhat distracting.

(The icons suggested in #77 are great, by the way)

**Comment by rafaelmardojai** [comment]
Yeah, I feel the same. But with #77 we will introduce an outline icon style, so the new icon will be gone.

I'm closing this since the new brighter icon hasn't been released.
