### ISSUE TITLE
copyright of sound tracks

### ISSUE THREAD

**Issue by apandada1** [rafaelmardojai/blanket#85]
I am planning to submit v0.3.1 to the official Debian repositories because v0.4 may still take some time.
The Debian developers are very strict about copyright of the files uploaded.
It may be a good idea to list the copyright info/credits of all the sound tracks in the README or another file so that we can use that to package for Debian and other distributions.

**Comment by rafaelmardojai** [comment]
There's some info about the clips in [this doc](https://github.com/rafaelmardojai/blanket/blob/master/doc/Sound_documentation.md). The sounds with `Unknown` license are creative commons, but i haven't the time to checkout the exact license.

 I will try to make a complete doc about sounds copyright soon.

**Comment by rafaelmardojai** [comment]
Now you can checkout this file https://github.com/rafaelmardojai/blanket/blob/master/SOUNDS_LICENSING.md for sounds licensing info.
