### ISSUE TITLE
A indicator in top bar for ubuntu and auto-start on startup option

### ISSUE THREAD

**Issue by preIdiot** [rafaelmardojai/blanket#91]
I really like the feature of keep playing the sound when closed, but it will be super awesome if I can control the extension from the top bar plus an option of auto-startup.
Please !!

**Comment by rafaelmardojai** [comment]
This is a duplicated of  #44 and #65. 

The auto-start on startup option will be implemented soon with the `xdg-desktop-portal` APIs.

About the indicator, this app already provides MPRIS integration, so you can control the app with the media controls of your desktop (see #14).
