### ISSUE TITLE
"AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'" when running on latest version from OpenSUSE repos

### ISSUE THREAD

**Issue by lomapur** [rafaelmardojai/blanket#92]
Hello,

first of all - great application!

Problem:

After installing from repos on latest snapshot of OpenSUSE Tumbleweed Blanket does not start:

    Traceback (most recent call last):
    File "/usr/bin/blanket", line 48, in <module>
    from blanket import main
    File "/usr/share/blanket/blanket/main.py", line 34, in <module>
    from .window import BlanketWindow
    File "/usr/share/blanket/blanket/window.py", line 24, in <module>
    from .widgets import SoundsGroup
    File "/usr/share/blanket/blanket/widgets.py", line 28, in <module>
    @Gtk.Template(resource_path='/com/rafaelmardojai/Blanket/sound-row.ui')
    File "/usr/lib64/python3.8/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
    AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'

Additional info:

    $ python3
    Python 3.8.7 (default, Dec 22 2020, 08:33:13) [GCC] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    import gi
    gi.version_info
    (3, 38, 0)

Blanket version 0.3.1.

I didn't try with Flatpak yet.

**Comment by rafaelmardojai** [comment]
I only maintain the Flatpak package. Any other method is provided by the community.

@jubalh any ideas?

**Comment by jubalh** [comment]
Strange. For me it runs perfectly. But I'm a few snapshots behind. Will take a look at it soon.

**Comment by Conan-Kudo** [comment]
I made some minor improvements in #94, but it seems like the overarching issue is that we're not requesting typelibs with the version. This would cause issues with gtk4 and gtk3 both being present on the same system, among other things.

**Comment by jubalh** [comment]
@lomapur I updated to the latest snapshot today. Still works for me.

Can you tell me the output of `rpm -qR blanket` and `cat /etc/os-release | grep VERSION` ?

**Comment by lomapur** [comment]
Sure, I updated yesterday (problem still persists):

    $ rpm -qR blanket
    /usr/bin/python3
    rpmlib(CompressedFileNames) <= 3.0.4-1
    rpmlib(FileDigests) <= 4.6.0-1
    rpmlib(PayloadFilesHavePrefix) <= 4.0-1
    rpmlib(PayloadIsZstd) <= 5.4.18-1
    typelib(GLib)
    typelib(GObject)
    typelib(Gdk) = 3.0
    typelib(Gio)
    typelib(Gst) = 1.0
    typelib(GstPlayer) = 1.0
    typelib(Gtk) = 3.0
    typelib(Handy) = 1

os-release:

    $ cat /etc/os-release | grep VERSION
    # VERSION="20210223"
    VERSION_ID="20210223"`

**Comment by jubalh** [comment]
I found https://gitlab.gnome.org/GNOME/pygobject/-/issues/423 which is about PyGObject not being updated for gtk4 yet. Maybe it is related.

**Comment by rafaelmardojai** [comment]
> I found https://gitlab.gnome.org/GNOME/pygobject/-/issues/423 which is about PyGObject not being updated for gtk4 yet. Maybe it is related.

It could affect a GTK3 app?
